---

- name: Install MetalLb.
  command: "{{ item }}"
  with_items:
    - kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.9.5/manifests/namespace.yaml
    - kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.9.5/manifests/metallb.yaml
  register: mllbcreate
  when: primarymanager is defined
  changed_when: false

- name: Configure MetalLb memberlist.
  shell: 'kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"'
  ignore_errors: yes
  when: primarymanager is defined
  changed_when: false

- name: Setup k8s MetalLb
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config
        namespace: metallb-system
      data:
        config: "{{ metallbpools }}"
  when: primarymanager is defined
